// bible-data.js -- generated by generate_bible.ps1
// ES3-compatible: var declaration, plain object literals
var BIBLE_DATA = [
  {
    num: 1,
    abbr: "Gen",
    name: "Genesis",
    folder: "01-Gen",
    chapters: [31, 25, 24, 26, 32, 22, 24, 22, 29, 32, 32, 20, 18, 24, 21, 16, 27, 33, 38, 18, 34, 24, 20, 67, 34, 35, 46, 22, 35, 43, 55, 32, 20, 31, 29, 43, 36, 30, 23, 23, 57, 38, 34, 34, 28, 34, 31, 22, 33, 26]
  },
  {
    num: 2,
    abbr: "Exod",
    name: "Exodus",
    folder: "02-Exod",
    chapters: [22, 25, 22, 31, 23, 30, 25, 32, 35, 29, 10, 51, 22, 31, 27, 36, 16, 27, 25, 26, 36, 31, 33, 18, 40, 37, 21, 43, 46, 38, 18, 35, 23, 35, 35, 38, 29, 31, 43, 38]
  },
  {
    num: 3,
    abbr: "Lev",
    name: "Leviticus",
    folder: "03-Lev",
    chapters: [17, 16, 17, 35, 19, 30, 38, 36, 24, 20, 47, 8, 59, 57, 33, 34, 16, 30, 37, 27, 24, 33, 44, 23, 55, 46, 34]
  },
  {
    num: 4,
    abbr: "Num",
    name: "Numbers",
    folder: "04-Num",
    chapters: [54, 34, 51, 49, 31, 27, 89, 26, 23, 36, 35, 16, 33, 45, 41, 50, 13, 32, 22, 29, 35, 41, 30, 25, 18, 65, 23, 31, 40, 16, 54, 42, 56, 29, 34, 13]
  },
  {
    num: 5,
    abbr: "Deut",
    name: "Deuteronomy",
    folder: "05-Deut",
    chapters: [46, 37, 29, 49, 33, 25, 26, 20, 29, 22, 32, 32, 18, 29, 23, 22, 20, 22, 21, 20, 23, 30, 25, 22, 19, 19, 26, 68, 29, 20, 30, 52, 29, 12]
  },
  {
    num: 6,
    abbr: "Josh",
    name: "Joshua",
    folder: "06-Josh",
    chapters: [18, 24, 17, 24, 15, 27, 26, 35, 27, 43, 23, 24, 33, 15, 63, 10, 18, 28, 51, 9, 45, 34, 16, 33]
  },
  {
    num: 7,
    abbr: "Judg",
    name: "Judges",
    folder: "07-Judg",
    chapters: [36, 23, 31, 24, 31, 40, 25, 35, 57, 18, 40, 15, 25, 20, 20, 31, 13, 31, 30, 48, 25]
  },
  {
    num: 8,
    abbr: "Ruth",
    name: "Ruth",
    folder: "08-Ruth",
    chapters: [22, 23, 18, 22]
  },
  {
    num: 9,
    abbr: "1Sam",
    name: "1 Samuel",
    folder: "09-1Sam",
    chapters: [28, 36, 21, 22, 12, 21, 17, 22, 27, 27, 15, 25, 23, 52, 35, 23, 58, 30, 24, 42, 15, 23, 29, 22, 44, 25, 12, 25, 11, 31, 13]
  },
  {
    num: 10,
    abbr: "2Sam",
    name: "2 Samuel",
    folder: "10-2Sam",
    chapters: [27, 32, 39, 12, 25, 23, 29, 18, 13, 19, 27, 31, 39, 33, 37, 23, 29, 33, 43, 26, 22, 51, 39, 25]
  },
  {
    num: 11,
    abbr: "1Kgs",
    name: "1 Kings",
    folder: "11-1Kgs",
    chapters: [53, 46, 28, 34, 18, 38, 51, 66, 28, 29, 43, 33, 34, 31, 34, 34, 24, 46, 21, 43, 29, 53]
  },
  {
    num: 12,
    abbr: "2Kgs",
    name: "2 Kings",
    folder: "12-2Kgs",
    chapters: [18, 25, 27, 44, 27, 33, 20, 29, 37, 36, 21, 21, 25, 29, 38, 20, 41, 37, 37, 21, 26, 20, 37, 20, 30]
  },
  {
    num: 13,
    abbr: "1Chr",
    name: "1 Chronicles",
    folder: "13-1Chr",
    chapters: [54, 55, 24, 43, 26, 81, 40, 40, 44, 14, 47, 40, 14, 17, 29, 43, 27, 17, 19, 8, 30, 19, 32, 31, 31, 32, 34, 21, 30]
  },
  {
    num: 14,
    abbr: "2Chr",
    name: "2 Chronicles",
    folder: "14-2Chr",
    chapters: [17, 18, 17, 22, 14, 42, 22, 18, 31, 19, 23, 16, 22, 15, 19, 14, 19, 34, 11, 37, 20, 12, 21, 27, 28, 23, 9, 27, 36, 27, 21, 33, 25, 33, 27, 23]
  },
  {
    num: 15,
    abbr: "Ezra",
    name: "Ezra",
    folder: "15-Ezra",
    chapters: [11, 70, 13, 24, 17, 22, 28, 36, 15, 44]
  },
  {
    num: 16,
    abbr: "Neh",
    name: "Nehemiah",
    folder: "16-Neh",
    chapters: [11, 20, 32, 23, 19, 19, 73, 18, 38, 39, 36, 47, 31]
  },
  {
    num: 17,
    abbr: "Esth",
    name: "Esther",
    folder: "17-Esth",
    chapters: [22, 23, 15, 17, 14, 14, 10, 17, 32, 3]
  },
  {
    num: 18,
    abbr: "Job",
    name: "Job",
    folder: "18-Job",
    chapters: [22, 13, 26, 21, 27, 30, 21, 22, 35, 22, 20, 25, 28, 22, 35, 22, 16, 21, 29, 29, 34, 30, 17, 25, 6, 14, 23, 28, 25, 31, 40, 22, 33, 37, 16, 33, 24, 41, 30, 24, 34, 17]
  },
  {
    num: 19,
    abbr: "Ps",
    name: "Psalms",
    folder: "19-Ps",
    chapters: [6, 12, 8, 8, 12, 10, 17, 9, 20, 18, 7, 8, 6, 7, 5, 11, 15, 50, 14, 9, 13, 31, 6, 10, 22, 12, 14, 9, 11, 12, 24, 11, 22, 22, 28, 12, 40, 22, 13, 17, 13, 11, 5, 26, 17, 11, 9, 14, 20, 23, 19, 9, 6, 7, 23, 13, 11, 11, 17, 12, 8, 12, 11, 10, 13, 20, 7, 35, 36, 5, 24, 20, 28, 23, 10, 12, 20, 72, 13, 19, 16, 8, 18, 12, 13, 17, 7, 18, 52, 17, 16, 15, 5, 23, 11, 13, 12, 9, 9, 5, 8, 28, 22, 35, 45, 48, 43, 13, 31, 7, 10, 10, 9, 8, 18, 19, 2, 29, 176, 7, 8, 9, 4, 8, 5, 6, 5, 6, 8, 8, 3, 18, 3, 3, 21, 26, 9, 8, 24, 13, 10, 7, 12, 15, 21, 10, 20, 14, 9, 6]
  },
  {
    num: 20,
    abbr: "Prov",
    name: "Proverbs",
    folder: "20-Prov",
    chapters: [33, 22, 35, 27, 23, 35, 27, 36, 18, 32, 31, 28, 25, 35, 33, 33, 28, 24, 29, 30, 31, 29, 35, 34, 28, 28, 27, 28, 27, 33, 31]
  },
  {
    num: 21,
    abbr: "Eccl",
    name: "Ecclesiastes",
    folder: "21-Eccl",
    chapters: [18, 26, 22, 16, 20, 12, 29, 17, 18, 20, 10, 14]
  },
  {
    num: 22,
    abbr: "Song",
    name: "Song of Solomon",
    folder: "22-Song",
    chapters: [17, 17, 11, 16, 16, 13, 13, 14]
  },
  {
    num: 23,
    abbr: "Isa",
    name: "Isaiah",
    folder: "23-Isa",
    chapters: [31, 22, 26, 6, 30, 13, 25, 22, 21, 34, 16, 6, 22, 32, 9, 14, 14, 7, 25, 6, 17, 25, 18, 23, 12, 21, 13, 29, 24, 33, 9, 20, 24, 17, 10, 22, 38, 22, 8, 31, 29, 25, 28, 28, 25, 13, 15, 22, 26, 11, 23, 15, 12, 17, 13, 12, 21, 14, 21, 22, 11, 12, 19, 12, 25, 24]
  },
  {
    num: 24,
    abbr: "Jer",
    name: "Jeremiah",
    folder: "24-Jer",
    chapters: [19, 37, 25, 31, 31, 30, 34, 22, 26, 25, 23, 17, 27, 22, 21, 21, 27, 23, 15, 18, 14, 30, 40, 10, 38, 24, 22, 17, 32, 24, 40, 44, 26, 22, 19, 32, 21, 28, 18, 16, 18, 22, 13, 30, 5, 28, 7, 47, 39, 46, 64, 34]
  },
  {
    num: 25,
    abbr: "Lam",
    name: "Lamentations",
    folder: "25-Lam",
    chapters: [22, 22, 66, 22, 22]
  },
  {
    num: 26,
    abbr: "Ezek",
    name: "Ezekiel",
    folder: "26-Ezek",
    chapters: [28, 10, 27, 17, 17, 14, 27, 18, 11, 22, 25, 28, 23, 23, 8, 63, 24, 32, 14, 49, 32, 31, 49, 27, 17, 21, 36, 26, 21, 26, 18, 32, 33, 31, 15, 38, 28, 23, 29, 49, 26, 20, 27, 31, 25, 24, 23, 35]
  },
  {
    num: 27,
    abbr: "Dan",
    name: "Daniel",
    folder: "27-Dan",
    chapters: [21, 49, 30, 37, 31, 28, 28, 27, 27, 21, 45, 13]
  },
  {
    num: 28,
    abbr: "Hos",
    name: "Hosea",
    folder: "28-Hos",
    chapters: [11, 23, 5, 19, 15, 11, 16, 14, 17, 15, 12, 14, 16, 9]
  },
  {
    num: 29,
    abbr: "Joel",
    name: "Joel",
    folder: "29-Joel",
    chapters: [20, 32, 21]
  },
  {
    num: 30,
    abbr: "Amos",
    name: "Amos",
    folder: "30-Amos",
    chapters: [15, 16, 15, 13, 27, 14, 17, 14, 15]
  },
  {
    num: 31,
    abbr: "Obad",
    name: "Obadiah",
    folder: "31-Obad",
    chapters: [21]
  },
  {
    num: 32,
    abbr: "Jonah",
    name: "Jonah",
    folder: "32-Jonah",
    chapters: [17, 10, 10, 11]
  },
  {
    num: 33,
    abbr: "Mic",
    name: "Micah",
    folder: "33-Mic",
    chapters: [16, 13, 12, 13, 15, 16, 20]
  },
  {
    num: 34,
    abbr: "Nah",
    name: "Nahum",
    folder: "34-Nah",
    chapters: [15, 13, 19]
  },
  {
    num: 35,
    abbr: "Hab",
    name: "Habakkuk",
    folder: "35-Hab",
    chapters: [17, 20, 19]
  },
  {
    num: 36,
    abbr: "Zeph",
    name: "Zephaniah",
    folder: "36-Zeph",
    chapters: [18, 15, 20]
  },
  {
    num: 37,
    abbr: "Hag",
    name: "Haggai",
    folder: "37-Hag",
    chapters: [15, 23]
  },
  {
    num: 38,
    abbr: "Zech",
    name: "Zechariah",
    folder: "38-Zech",
    chapters: [21, 13, 10, 14, 11, 15, 14, 23, 17, 12, 17, 14, 9, 21]
  },
  {
    num: 39,
    abbr: "Mal",
    name: "Malachi",
    folder: "39-Mal",
    chapters: [14, 17, 18, 6]
  },
  {
    num: 40,
    abbr: "Matt",
    name: "Matthew",
    folder: "40-Matt",
    chapters: [25, 23, 17, 25, 48, 34, 29, 34, 38, 42, 30, 50, 58, 36, 39, 28, 27, 35, 30, 34, 46, 46, 39, 51, 46, 75, 66, 20]
  },
  {
    num: 41,
    abbr: "Mark",
    name: "Mark",
    folder: "41-Mark",
    chapters: [45, 28, 35, 41, 43, 56, 37, 38, 50, 52, 33, 44, 37, 72, 47, 20]
  },
  {
    num: 42,
    abbr: "Luke",
    name: "Luke",
    folder: "42-Luke",
    chapters: [80, 52, 38, 44, 39, 49, 50, 56, 62, 42, 54, 59, 35, 35, 32, 31, 37, 43, 48, 47, 38, 71, 56, 53]
  },
  {
    num: 43,
    abbr: "John",
    name: "John",
    folder: "43-John",
    chapters: [51, 25, 36, 54, 47, 71, 53, 59, 41, 42, 57, 50, 38, 31, 27, 33, 26, 40, 42, 31, 25]
  },
  {
    num: 44,
    abbr: "Acts",
    name: "Acts",
    folder: "44-Acts",
    chapters: [26, 47, 26, 37, 42, 15, 60, 40, 43, 48, 30, 25, 52, 28, 41, 40, 34, 28, 41, 38, 40, 30, 35, 27, 27, 32, 44, 31]
  },
  {
    num: 45,
    abbr: "Rom",
    name: "Romans",
    folder: "45-Rom",
    chapters: [32, 29, 31, 25, 21, 23, 25, 39, 33, 21, 36, 21, 14, 23, 33, 27]
  },
  {
    num: 46,
    abbr: "1Cor",
    name: "1 Corinthians",
    folder: "46-1Cor",
    chapters: [31, 16, 23, 21, 13, 20, 40, 13, 27, 33, 34, 31, 13, 40, 58, 24]
  },
  {
    num: 47,
    abbr: "2Cor",
    name: "2 Corinthians",
    folder: "47-2Cor",
    chapters: [24, 17, 18, 18, 21, 18, 16, 24, 15, 18, 33, 21, 14]
  },
  {
    num: 48,
    abbr: "Gal",
    name: "Galatians",
    folder: "48-Gal",
    chapters: [24, 21, 29, 31, 26, 18]
  },
  {
    num: 49,
    abbr: "Eph",
    name: "Ephesians",
    folder: "49-Eph",
    chapters: [23, 22, 21, 32, 33, 24]
  },
  {
    num: 50,
    abbr: "Phil",
    name: "Philippians",
    folder: "50-Phil",
    chapters: [30, 30, 21, 23]
  },
  {
    num: 51,
    abbr: "Col",
    name: "Colossians",
    folder: "51-Col",
    chapters: [29, 23, 25, 18]
  },
  {
    num: 52,
    abbr: "1Thess",
    name: "1 Thessalonians",
    folder: "52-1Thess",
    chapters: [10, 20, 13, 18, 28]
  },
  {
    num: 53,
    abbr: "2Thess",
    name: "2 Thessalonians",
    folder: "53-2Thess",
    chapters: [12, 17, 18]
  },
  {
    num: 54,
    abbr: "1Tim",
    name: "1 Timothy",
    folder: "54-1Tim",
    chapters: [20, 15, 16, 16, 25, 21]
  },
  {
    num: 55,
    abbr: "2Tim",
    name: "2 Timothy",
    folder: "55-2Tim",
    chapters: [18, 26, 17, 22]
  },
  {
    num: 56,
    abbr: "Titus",
    name: "Titus",
    folder: "56-Titus",
    chapters: [16, 15, 15]
  },
  {
    num: 57,
    abbr: "Phlm",
    name: "Philemon",
    folder: "57-Phlm",
    chapters: [25]
  },
  {
    num: 58,
    abbr: "Heb",
    name: "Hebrews",
    folder: "58-Heb",
    chapters: [14, 18, 19, 16, 14, 20, 28, 13, 28, 39, 40, 29, 25]
  },
  {
    num: 59,
    abbr: "Jas",
    name: "James",
    folder: "59-Jas",
    chapters: [27, 26, 18, 17, 20]
  },
  {
    num: 60,
    abbr: "1Pet",
    name: "1 Peter",
    folder: "60-1Pet",
    chapters: [25, 25, 22, 19, 14]
  },
  {
    num: 61,
    abbr: "2Pet",
    name: "2 Peter",
    folder: "61-2Pet",
    chapters: [21, 22, 18]
  },
  {
    num: 62,
    abbr: "1John",
    name: "1 John",
    folder: "62-1John",
    chapters: [10, 29, 24, 21, 21]
  },
  {
    num: 63,
    abbr: "2John",
    name: "2 John",
    folder: "63-2John",
    chapters: [13]
  },
  {
    num: 64,
    abbr: "3John",
    name: "3 John",
    folder: "64-3John",
    chapters: [14]
  },
  {
    num: 65,
    abbr: "Jude",
    name: "Jude",
    folder: "65-Jude",
    chapters: [25]
  },
  {
    num: 66,
    abbr: "Rev",
    name: "Revelation",
    folder: "66-Rev",
    chapters: [20, 29, 22, 11, 14, 17, 17, 13, 21, 11, 19, 17, 18, 20, 8, 21, 18, 24, 21, 15, 27, 21]
  },
];
